// Объект с текстами копирайтов для каждого языка
export const COPYRIGHTS = {
  labelName: {
    ru: 'Имя',
    en: 'Name',
    es: 'Nombre',
    de: 'Name',
    fr: 'Nom',
    it: 'Nome',
    pl: 'Nazwa',
    zh: '姓名',
    tr: 'Ad',
    hi: 'नाम',
    pt: 'Nome',
    ja: '名前',
    ar: 'الاسم',
    fa: 'نام',
  },
  labelNameRequired: {
    ru: 'Ваше имя *',
    en: 'Your name *',
    es: 'Su nombre *',
    de: 'Ihren Namen *',
    fr: 'Votre nom *',
    it: 'Il tuo nome *',
    pl: 'Twoje imię *',
    zh: '你的名字 *',
    tr: 'İsminiz *',
    hi: 'अप का नाम *',
    pt: 'Seu nome *',
    ja: 'あなたの名前 *',
    ar: 'اسمك *',
    fa: 'نام شما *',
  },
  placeholderName: {
    ru: 'Ваше имя',
    en: 'Your name',
    es: 'Su nombre',
    de: 'Ihren Namen',
    fr: 'Votre nom',
    it: 'Il tuo nome',
    pl: 'Twoje imię',
    zh: '你的名字',
    tr: 'İsminiz',
    hi: 'अप का नाम',
    pt: 'Seu nome',
    ja: 'あなたの名前',
    ar: 'اسمك',
    fa: 'نام شما',
  },
  labelLastName: {
    ru: 'Фамилия',
    en: 'Last name',
    es: 'Apellido',
    de: 'Familienname',
    fr: 'Nom de famille',
    it: 'Cognome',
    pl: 'Nazwisko',
    zh: '姓',
    tr: 'Soyadı',
    hi: 'उपनाम',
    pt: 'Sobrenome',
    ja: '苗字',
    ar: 'اللقب',
    fa: 'نام خانوادگی',
  },
  labelLastNameRequired: {
    ru: 'Ваша фамилия *',
    en: 'Your last name *',
    es: 'Tu apellido *',
    de: 'Ihr Nachname *',
    fr: 'Votre nom de famille *',
    it: 'Il tuo cognome *',
    pl: 'Twoje nazwisko *',
    zh: '你的姓氏 *',
    tr: 'Soyadınız *',
    hi: 'आपका अंतिम नाम *',
    pt: 'Seu sobrenome *',
    ja: 'あなたの苗字 *',
    ar: 'اسم العائلة الخاص بك *',
    fa: 'نام خانوادگی *',
  },
  placeholderLastName: {
    ru: 'Ваша фамилия',
    en: 'Your last name',
    es: 'Tu apellido',
    de: 'Ihr Nachname',
    fr: 'Votre nom de famille',
    it: 'Il tuo cognome',
    pl: 'Twoje nazwisko',
    zh: '你的姓氏',
    tr: 'Soyadınız',
    hi: 'आपका अंतिम नाम',
    pt: 'Seu sobrenome',
    ja: 'あなたの苗字',
    ar: 'اسم العائلة الخاص بك',
    fa: 'نام خانوادگی',
  },
  lastNames: {
    ru: 'Фамилия',
    en: 'Last name',
    es: 'Apellido',
    de: 'Familienname',
    fr: 'Nom de famille',
    it: 'Cognome',
    pl: 'Nazwisko',
    zh: '姓',
    tr: 'Soyadı',
    hi: 'उपनाम ',
    pt: 'Sobrenome',
    ja: '苗字',
    ar: 'اسم العائلة',
    fa: 'نام خانوادگی',
  },
  lastNamesTitle: {
    ru: 'Ваша фамилия',
    en: 'Your last name',
    es: 'Tu apellido',
    de: 'Ihr Nachname',
    fr: 'Votre nom de famille',
    it: 'Il tuo cognome',
    pl: 'Twoje nazwisko',
    zh: '你的姓氏',
    tr: 'Soyadınız',
    hi: 'आपका अंतिम नाम ',
    pt: 'Seu sobrenome',
    ja: 'あなたの苗字',
    ar: 'اسم العائلة الخاص بك',
    fa: 'نام خانوادگی',
  },
  labelMail: {
    ru: 'E-mail',
    en: 'Email',
    es: 'Correo electrónico',
    de: 'Email',
    fr: 'E-mail',
    it: 'E-mail',
    pl: 'E-mail',
    zh: '电子邮件',
    tr: 'E-posta',
    hi: 'ईमेल',
    pt: 'E-mail',
    ja: 'メール',
    ar: 'البريد الإلكتروني',
    fa: 'ایمیل',
  },
  placeholderEmail: {
    ru: 'Ваш E-mail',
    en: 'Your Email',
    es: 'Tu correo electrónico',
    de: 'Deine E-Mail',
    fr: 'Votre e-mail',
    it: 'La tua email',
    pl: 'Twój email',
    zh: '你的邮件',
    tr: 'E-postanız',
    hi: 'आपका ईमेल',
    pt: 'Seu e-mail',
    ja: 'あなたのメール',
    ar: 'بريدك الإلكتروني',
    fa: 'ایمیل شما',
  },
  labelEmailRequired: {
    ru: 'Ваш E-mail *',
    en: 'Your Email *',
    es: 'Tu correo electrónico *',
    de: 'Deine E-Mail *',
    fr: 'Votre e-mail *',
    it: 'La tua email *',
    pl: 'Twój email *',
    zh: '你的邮件 *',
    tr: 'E-postanız *',
    hi: 'आपका ईमेल *',
    pt: 'Seu e-mail *',
    ja: 'あなたのメール *',
    ar: 'بريدك الإلكتروني *',
    fa: 'ایمیل شما *',
  },
  labelPassword: {
    ru: 'Пароль',
    en: 'Password',
    es: 'Contraseña',
    de: 'Passwort',
    fr: 'Mot de passe',
    it: "Parola d'ordine",
    pl: 'Hasło',
    zh: '密码',
    tr: 'Şifre',
    hi: 'पासवर्ड',
    pt: 'Senha',
    ja: 'パスワード',
    ar: 'كلمة المرور',
    fa: 'رمز عبور',
  },
  labelPasswordRequired: {
    ru: 'Пароль *',
    en: 'Password *',
    es: 'Contraseña *',
    de: 'Passwort *',
    fr: 'Mot de passe *',
    it: "Parola d'ordine *",
    pl: 'Hasło *',
    zh: '密码 *',
    tr: 'Şifre *',
    hi: 'पासवर्ड *',
    pt: 'Senha *',
    ja: 'パスワード *',
    ar: 'كلمة المرور *',
    fa: 'رمز عبور *',
  },
  placeholderPassword: {
    ru: 'Введите пароль',
    en: 'Enter password',
    es: 'Introducir la contraseña',
    de: 'Passwort eingeben',
    fr: 'Entrer le mot de passe',
    it: 'Inserire la password',
    pl: 'Wprowadź hasło',
    zh: '输入密码',
    tr: 'Şifreyi giriniz',
    hi: 'पास वर्ड दर्ज करें',
    pt: 'Digite a senha',
    ja: 'パスワードを入力してください',
    ar: 'أدخل كلمة المرور',
    fa: 'رمز عبور را وارد کنید',
  },
  labelConfirmPassword: {
    ru: 'Подтвердите пароль',
    en: 'Confirm the password',
    es: 'Confirmar la contraseña',
    de: 'Bestätigen Passwort',
    fr: 'Confirmez de passe',
    it: 'Conferma la password',
    pl: 'Potwierdź hasło',
    zh: '确认密码',
    tr: 'Şifreyi onaylayınız',
    hi: 'पासवर्ड की पुष्टि करें',
    pt: 'Confirme a senha',
    ja: 'パスワードを確認',
    ar: 'تأكيد كلمة المرور',
    fa: 'رمز عبور را تأیید کنید',
  },
  labelConfirmPasswordRequired: {
    ru: 'Подтвердите пароль *',
    en: 'Confirm the password *',
    es: 'Confirmar la contraseña *',
    de: 'Bestätigen Passwort *',
    fr: 'Confirmez de passe *',
    it: 'Conferma la password *',
    pl: 'Potwierdź hasło *',
    zh: '确认密码 *',
    tr: 'Şifreyi onaylayınız *',
    hi: 'पासवर्ड की पुष्टि करें *',
    pt: 'Confirme a senha *',
    ja: 'パスワードを確認 *',
    ar: 'تأكيد كلمة المرور *',
    fa: 'رمز عبور را تأیید کنید *',
  },
  placeholderConfirmPassword: {
    ru: 'Подтвердите пароль',
    en: 'Confirm the password',
    es: 'Confirmar la contraseña',
    de: 'Bestätigen Passwort',
    fr: 'Confirmez de passe',
    it: 'Conferma la password',
    pl: 'Potwierdź hasło',
    zh: '确认密码',
    tr: 'Şifreyi onaylayınız',
    hi: 'पासवर्ड की पुष्टि करें',
    pt: 'Confirme a senha',
    ja: 'パスワードを確認してください',
    ar: 'تأكيد كلمة المرور',
    fa: 'رمز عبور را تأیید کنید',
  },
  labelPhone: {
    ru: 'Телефон',
    en: 'Phone',
    es: 'Teléfono',
    de: 'Telefon',
    fr: 'Téléphone',
    it: 'Telefono',
    pl: 'Telefon',
    zh: '电话',
    tr: 'Telefon',
    hi: 'फ़ोन',
    pt: 'Telefone',
    ja: '電話',
    ar: 'الهاتف',
    fa: 'تلفن',
  },
  placeholderPhone: {
    ru: 'Ваш телефон',
    en: 'Your phone number',
    es: 'Su número de teléfono',
    de: 'Deine Telefonnummer',
    fr: 'Votre numéro de téléphone',
    it: 'Il tuo numero di telefono',
    pl: 'Twój numer telefonu',
    zh: '你的电话号码',
    tr: 'Telefon numaranız',
    hi: 'आपका फोन नंबर',
    pt: 'Seu número de telefone',
    ja: 'あなたの電話番号',
    ar: 'رقم هاتفك',
    fa: 'شماره تلفن شما',
  },
  labelPhoneRequired: {
    ru: 'Ваш телефон *',
    en: 'Your phone number *',
    es: 'Su número de teléfono *',
    de: 'Deine Telefonnummer *',
    fr: 'Votre numéro de téléphone *',
    it: 'Il tuo numero di telefono *',
    pl: 'Twój numer telefonu *',
    zh: '你的电话号码 *',
    tr: 'Telefon numaranız *',
    hi: 'आपका फोन नंबर *',
    pt: 'Seu número de telefone *',
    ja: 'あなたの電話番号 *',
    ar: 'رقم هاتفك *',
    fa: 'شماره تلفن شما *',
  },
  placeholderCaptcha: {
    ru: 'Введите каптчу',
    en: 'Enter captcha',
    es: 'Introduzca el captcha',
    de: 'Captcha eingeben',
    fr: 'Entrez le captcha',
    it: 'Inserisci captcha',
    pl: 'Wprowadź captcha',
    zh: '输入验证码',
    tr: 'Captcha girin',
    hi: 'कैप्चा दर्ज करें',
    pt: 'Digite o captcha',
    ja: 'キャプチャを入力',
    ar: 'أدخل رمز التحقق',
    fa: 'کپچا را وارد کنید',
  },
  loading: {
    ru: 'Отправка...',
    en: 'Sending...',
    es: 'Envío...',
    de: 'Senden...',
    fr: 'Envoi...',
    it: 'Invio...',
    pl: 'Przesyłka...',
    zh: '发送...',
    tr: 'Gönderiliyor...',
    hi: 'भेजना...',
    pt: 'Enviando...',
    ja: '送信中...',
    ar: 'إرسال...',
    fa: 'در حال ارسال...',
  },
  labelTimes: {
    ru: 'Время, удобное для звонка',
    en: 'Preferred contact time',
    es: 'Hora de contacto preferida',
    de: 'Bevorzugte Kontaktzeit',
    fr: 'Heure de contact préférée',
    it: 'Orario di contatto preferito',
    pl: 'Preferowany czas kontaktu',
    zh: '首选联系时间',
    tr: 'Tercih edilen iletişim zamani',
    hi: 'पसंदीदा संपर्क समय',
    pt: 'Horário preferido de contato',
    ja: '希望する連絡時間',
    ar: 'الوقت المفضل للاتصال',
    fa: 'زمان تماس ترجیحی',
  },
  labelTimesZone: {
    ru: 'Часовой пояс',
    en: 'Time zone',
    es: 'Huso horario',
    de: 'Zeitzone',
    fr: 'Fuseau horaire',
    it: 'Il fuso orario',
    pl: 'Strefa czasowa',
    zh: '时区',
    tr: 'Zaman dilimi',
    hi: 'समय क्षेत्र',
    pt: 'Fuso horário',
    ja: 'タイムゾーン',
    ar: 'المنطقة الزمنية',
    fa: 'منطقه زمانی',
  },
  labelDates: {
    ru: 'Дата',
    en: 'Date',
    es: 'Fecha',
    de: 'Datum',
    fr: 'Date',
    it: 'Tempo conveniente',
    pl: 'Data',
    zh: '日期',
    tr: 'Tarihi',
    hi: 'तारीख',
    pt: 'Data',
    ja: '日付',
    ar: 'التاريخ',
    fa: 'تاریخ',
  },
  placeholderTimes: {
    ru: 'Время для звонка',
    en: 'Time to call',
    es: 'Hora de llamar',
    de: 'Zeit zu rufen',
    fr: "Il est temps d'appeler",
    it: 'È ora di chiamare',
    pl: 'Czas zadzwonić',
    zh: '是时候打电话了',
    tr: 'Tercih edilen iletişim zamani',
    hi: 'कॉल करने का समय',
    pt: 'Hora para ligar',
    ja: '電話する時間',
    ar: 'وقت الاتصال',
    fa: 'وقت تماس گرفتنه',
  },
  lableTwoauth: {
    ru: 'Код авторизации',
    en: 'Authorization code',
    es: 'Código de Autorización',
    de: 'Autorisierungscode',
    fr: "Code d'autorisation",
    it: 'Codice di autorizzazione',
    pl: 'Kod autoryzacji',
    zh: '授权代码',
    tr: 'Yetkilendirme kodu',
    hi: 'प्राधिकरण संकेत - लिपि',
    pt: 'Código de autorização',
    ja: '認証コード',
    ar: 'رمز التفويض',
    fa: 'کد مجوز',
  },
  placeholderTwoauth: {
    ru: 'Код двухэтапной авторизации',
    en: '2FA verification code',
    es: 'Código de verificación 2FA',
    de: '2FA-Verifizierungscode',
    fr: '2fa Code de vérification',
    it: 'Codice di verifica 2FA',
    pl: '2FA Kod weryfikacji',
    zh: '2FA验证代码',
    tr: 'İki faktörlü yetkilendirme kodu',
    hi: '2FA सत्यापन कोड',
    pt: 'Código de verificação 2FA',
    ja: '2FA認証コード',
    ar: 'رمز التحقق 2FA',
    fa: 'کد تأیید 2FA',
  },
  labelPromo: {
    ru: 'Промокод (необязательно)',
    en: 'Promo code (optional)',
    es: 'Código de promoción (Opcional)',
    de: 'Angebotscode (optional)',
    fr: 'Code promotionnel (Optionnel)',
    it: 'Codice Promozionale (Facoltativo)',
    pl: 'Kod Promocyjny (Opcjonalnie)',
    zh: '促销代码（可选）',
    tr: 'Promosyon kodu (isteğe bağlı)',
    hi: 'प्रोमो कोड (वैकल्पिक)',
    pt: 'Código promocional (opcional)',
    ja: 'プロモーションコード（オプション）',
    ar: 'رمز ترويجي (اختياري)',
    fa: 'کد تخفیف (اختیاری)',
  },
  placeholderPromo: {
    ru: 'Введите промокод',
    en: 'Enter promo code',
    es: 'Código promocional',
    de: 'Geben Sie den Promo',
    fr: 'Saisir le code promotionnel',
    it: 'Immettere il codice promozionale',
    pl: 'Wpisz kod promocyjny',
    zh: '输入促销代码',
    tr: 'Promosyon kodunu giriniz',
    hi: 'प्रचार कि नियमावली दर्ज करो',
    pt: 'Digite o código promocional',
    ja: 'プロモーションコード',
    ar: 'أدخل الرمز الترويجي',
    fa: 'کد تخفیف را وارد کنید',
  },
  placeholderMessage: {
    ru: 'Сообщение',
    en: 'Message',
    es: 'Mensaje',
    de: 'Nachricht schreiben',
    fr: 'Message',
    it: 'Messaggio',
    pl: 'Wiadomość',
    zh: '信息',
    tr: 'Mesaj',
    hi: 'संदेश',
    pt: 'Mensagem',
    ja: 'メッセージ',
    ar: 'رسالة',
    fa: 'پیام',
  },
  terms: {
    ru: 'Я ознакомлен и согласен с',
    en: 'I have read and agree to the',
    es: 'He leído y acepto la',
    de: 'Ich habe die Informationen gelesen und stimme ihnen zu',
    fr: "J'ai lu et j'accepte la",
    it: "Sono d'accordo",
    pl: 'Przeczytałem i zgadzam się na',
    zh: '我已阅读并同意',
    tr: 'Okudum ve kabul ediyorum',
    hi: 'मैंने',
    pt: 'Li e concordo com a',
    ja: '私は以下の内容を読み、同意します。',
    ar: 'تعرفت على',
    fa: 'من خوانده‌ام و با آن موافقم',
  },
  and: {
    ru: 'и',
    en: 'and',
    es: 'y',
    de: 'und die',
    fr: 'et',
    it: 'е',
    pl: 'i',
    zh: '和',
    tr: 've',
    hi: 'और',
    pt: 'e',
    ja: 'そして',
    ar: 'و',
    fa: 'و',
  },
  checkboxAgreement: {
    en: 'User Agreement',
    ru: 'Пользовательским соглашением',
    es: 'Acuerdo del Usuario',
    de: 'Nutzungs bedingungen',
    fr: "Accord de l'utilisateur",
    it: 'Accordo per gli utenti',
    pl: 'Zgoda użytkownika',
    zh: '用户协议',
    tr: 'Kullanım Şartları',
    hi: 'उपयोगकर्ता का समझौता',
    pt: 'Acordo do Usuário',
    ja: 'ユーザー契約',
    ar: 'اتفاقية المستخدم',
    fa: 'توافقنامه کاربری',
  },
  checkboxPolicy: {
    ru: 'Политикой конфиденциальности',
    en: 'Privacy Policy',
    es: 'Política de Privacidad',
    de: 'Datenschutzrichtlinie',
    fr: 'Politique de Confidentialité',
    it: 'Privacy Policy',
    pl: 'Polityka prywatności',
    zh: '隐私政策',
    tr: "Gizlilik Politikası'nı",
    hi: 'गोपनीयता नीति',
    pt: 'Política de Privacidade',
    ja: 'プライバシーポリシー',
    ar: 'سياسة السرية',
    fa: 'سیاست حفظ حریم خصوصی',
  },
  checkboxTerms: {
    ru: 'Условиями использования',
    en: 'Terms of Use',
    es: 'Términos de Uso',
    de: 'Nutzungsbedingungen',
    fr: "Conditions d'Utilisation",
    it: 'Terms of Use',
    pl: 'Warunki użytkowania',
    zh: '使用条款',
    tr: "Kullanım Koşulları'nı",
    hi: 'उपयोग की शर्तों के लिए पढ़ा और सहमत हूं।',
    pt: 'Termos de Uso',
    ja: '利用規約',
    ar: 'شروط الاستخدام',
    fa: 'شرایط استفاده',
  },
  labelDepartments: {
    ru: 'Выбор отдела',
    en: 'Select a department',
    es: 'Seleccione un departamento',
    de: 'Wählen Sie eine Abteilung',
    fr: 'Sélectionnez un département',
    it: 'Selezione del dipartimento',
    pl: 'Wybierz dział',
    zh: '选择部门',
    tr: 'Bir departman seçin',
    hi: 'एक विभाग चुनें',
    pt: 'Selecione um departamento',
    ja: '部門を選択',
    ar: 'اختر القسم',
    fa: 'یک دپارتمان انتخاب کنید',
  },
  labelLanguages: {
    ru: 'Язык общения',
    en: 'Communication language',
    es: 'Lenguaje de comunicación',
    de: 'Kommunikation Sprache',
    fr: 'Langue de communication',
    it: 'Lingua di comunicazione',
    pl: 'Język komunikacji',
    zh: '溝通語言',
    tr: 'Iletişim dili',
    hi: 'संचार भाषा',
    pt: 'Idioma de comunicação',
    ja: 'コミュニケーション言語',
    ar: 'لغة التواصل',
    fa: 'زبان ارتباطی',
  },
  captchaTitle: {
    ru: 'Ввод текста с картинки',
    en: 'To enter the text from the image',
    es: 'Para ingresar el texto de la imagen',
    de: 'Um den Text aus dem Bild einzugeben',
    fr: "Pour saisir le texte de l'image",
    it: "Per inserire il testo dall'immagine",
    pl: 'Aby wprowadzić tekst z obrazka',
    zh: '输入图像中的文本',
    tr: 'Resimden metin girmek',
    hi: 'छवि से पाठ दर्ज करने के लिए',
    pt: 'Digite o texto da imagem',
    ja: '画像からテキストを入力してください',
    ar: 'أدخل النص من الصورة',
    fa: 'برای وارد کردن متن از تصویر',
  },
  licensePopupTitle: {
    ru: 'Для перехода на страницу необходимо ввести адрес электронной почты',
    en: 'To go to the page you must enter your email address',
    es: 'Para ir a la página debes ingresar tu dirección de correo electrónico',
    de: 'Um zur Seite zu gelangen, müssen Sie Ihre E-Mail-Adresse eingeben',
    fr: 'Pour accéder à la page, vous devez saisir votre adresse email',
    it: 'Per andare alla pagina devi inserire il tuo indirizzo email',
    pl: 'Aby przejść do strony należy podać swój adres e-mail',
    zh: '要转到该页面，您必须输入您的电子邮件地址',
    tr: 'Sayfaya gitmek için e-posta adresinizi girmelisiniz',
    hi: 'पेज पर जाने के लिए आपको अपना ईमेल पता दर्ज करना होगा',
    pt: 'Para ir para a página, você deve inserir seu endereço de e-mail',
    ja: 'ページに進むには、メールアドレスを入力してください',
    ar: 'للانتقال إلى الصفحة، يجب إدخال عنوان بريدك الإلكتروني',
    fa: 'برای رفتن به صفحه باید آدرس ایمیل خود را وارد کنید',
  },
  recoveryText: {
    ru: 'Введите адрес электронной почты и мы вышлем вам временный пароль для входа.',
    en: "Enter your email and we'll send you a temporary password to log in.",
    es: 'Ingrese su correo electrónico y le enviaremos una contraseña temporal para iniciar sesión.',
    de: 'Geben Sie Ihre E-Mail ein und wir senden Ihnen ein temporäres Passwort, um sich anzumelde.',
    fr: 'Entrez votre e-mail et nous vous enverrons un mot de passe temporaire pour vous connecter.',
    it: 'Inserisci la tua e-mail e ti invieremo una password temporanea per accedere.',
    pl: 'Wprowadź swój e-mail, a my wyślemy Ci tymczasowe hasło do zalogowania się.',
    zh: '输入您的电子邮件，我们将向您发送临时密码以登录。',
    tr: 'E-postanızı girin ve giriş yapmak için size geçici bir şifre gönderelim.',
    hi: 'अपना ईमेल दर्ज करें और हम आपको लॉग इन करने के लिए एक अस्थायी पासवर्ड भेजेंगे',
    pt: 'Digite seu e-mail e enviaremos uma senha temporária para fazer login.',
    ja: 'メールアドレスを入力すると、ログイン用の一時パスワードを送信します。',
    ar: 'أدخل بريدك الإلكتروني وسنرسل لك كلمة مرور مؤقتة لتسجيل الدخول.',
    fa: 'ایمیل خود را وارد کنید تا یک رمز عبور موقت برای ورود به سیستم برای شما ارسال کنیم.',
  },
  titleTwoauth: {
    ru: 'Двухфакторная авторизация',
    en: '2FA Authorization',
    es: 'Autorización de 2FA',
    de: '2fa Autorisierung',
    fr: 'Autorisation 2FA',
    it: '2FA Autorizzazione',
    pl: 'Upoważnienie 2FA',
    zh: '2FA授权',
    tr: 'İki faktörlü yetkilendirme',
    hi: '2FA प्राधिकरण',
    pt: 'Autorização 2FA',
    ja: '2FA認証',
    ar: 'تفويض 2FA',
    fa: 'احراز هویت دو مرحله‌ای (2FA)',
  },
  titleTwoauthGoogle: {
    ru: 'Используйте приложение Google Authenticator',
    en: 'Use the Google Authenticator app',
    es: 'Use the Google Authenticator app',
    de: 'Use the Google Authenticator app',
    fr: 'Use the Google Authenticator app',
    it: 'Use the Google Authenticator app',
    pl: 'Use the Google Authenticator app',
    zh: 'Use the Google Authenticator app',
    tr: 'Use the Google Authenticator app',
    hi: 'Use the Google Authenticator app',
    pt: 'Use the Google Authenticator app',
    ja: 'Use the Google Authenticator app',
    ar: 'Use the Google Authenticator app',
    fa: 'از برنامه Google Authenticator استفاده کنید',
  },
  titleTwoauthEmail: {
    ru: 'Авторизация по Email коду',
    en: 'Authorization by Email code',
    es: 'Autorización por código de correo electrónico',
    de: 'Autorisierung per E-Mail-Code',
    fr: 'Autorisation par code Email',
    it: 'Autorizzazione tramite codice e-mail',
    pl: 'Autoryzacja za pomocą kodu e-mail',
    zh: '通过电子邮件代码授权',
    tr: 'E-posta koduyla yetkilendirme',
    hi: 'ईमेल कोड द्वारा प्राधिकरण',
    pt: 'Autorização por código de e-mail',
    ja: 'メールコードによる認証',
    ar: 'التفويض عبر رمز البريد الإلكتروني',
    fa: 'مجوز از طریق کد ایمیل',
  },
  enterCode: {
    ru: 'Введите код',
    en: 'Enter code',
    es: 'Introducir código',
    de: 'Code eingeben',
    fr: 'Entrer le code',
    it: 'Inserisci il codice',
    pl: 'Wprowadź kod',
    zh: '输入代码',
    tr: 'Kodu girin',
    hi: 'कोड दर्ज करें',
    pt: 'Digite o código',
    ja: 'コードを入力してください',
    ar: 'أدخل الرمز',
    fa: 'کد را وارد کنید',
  },
  titleSuccess: {
    ru: 'Ваш запрос отправлен',
    en: 'Your request has been sent',
    es: 'Tu solicitud ha sido enviada',
    de: 'Ihre Anfrage wurde verschickt',
    fr: 'Votre demande à été envoyé',
    it: 'La tua richiesta è stata inviata',
    pl: 'Twoje zapytanie zostało wysłane',
    zh: '您的申请已经提交',
    tr: 'İsteğiniz gönderildi',
    hi: 'आपका अनुरोध भेज दिया गया है',
    pt: 'Sua solicitação foi enviada',
    ja: 'リクエストが送信されました',
    ar: 'تم إرسال طلبك',
    fa: 'درخواست شما ارسال شد',
  },
  textSuccess: {
    ru: 'Мы свяжемся с вами в ближайшее время',
    en: 'We will contact you shortly',
    es: 'Nos comunicaremos con usted en breve',
    de: 'Wir werden Sie in Kürze kontaktieren',
    fr: 'Nous vous contacterons sous peu',
    it: 'Ti contatteremo a breve',
    pl: 'Wkrótce skontaktujemy się z Tobą',
    zh: '我们会尽快与您联系',
    tr: 'Yakında sizinle iletişime geçeceğiz',
    hi: 'हम आपसे शीघ्र ही संपर्क करेंगे',
    pt: 'Entraremos em contato em breve',
    ja: 'すぐにご連絡いたします',
    ar: 'سنتصل بك قريبًا',
    fa: 'به زودی با شما تماس خواهیم گرفت',
  },
  titleError: {
    ru: 'Ваш запрос не отправлен',
    en: 'Your request was not sent',
    es: 'Tu solicitud no fue enviada',
    de: 'Ihre Anfrage wurde nicht gesendet',
    fr: "Votre demande n'a pas été envoyée",
    it: 'La tua richiesta non è stata inviata',
    pl: 'Twoja prośba nie została wysłana',
    zh: '您的要求未发送',
    tr: 'İsteğiniz gönderilmedi',
    hi: 'आपका अनुरोध नहीं भेजा गया था',
    pt: 'Sua solicitação não foi enviada',
    ja: 'リクエストが送信されませんでした',
    ar: 'لم يتم إرسال طلبك',
    fa: 'درخواست شما ارسال نشد',
  },
  textError: {
    ru: 'Что-то пошло не так! Проверьте корректность введенной информации или попробуйте повторить попытку позже.',
    en: 'Something went wrong! Please check that the information you entered is correct or try again later.',
    es: '¡Algo salió mal! Verifique que la información que ingresó sea correcta o vuelva a intentarlo más tarde.',
    de: 'Etwas ist schief gelaufen! Bitte überprüfen Sie, ob die von Ihnen eingegebenen Informationen korrekt sind, oder versuchen Sie es später erneut.',
    fr: "Quelque chose s'est mal passé! Veuillez vérifier que les informations que vous avez saisies sont correctes ou réessayer plus tard.",
    it: 'Qualcosa è andato storto! Si prega di verificare che le informazioni inserite siano corrette o riprova più tardi.',
    pl: 'Coś poszło nie tak! Sprawdź, czy wprowadzone informacje są poprawne lub spróbuj ponownie później.',
    zh: '出了些问题！请检查您输入的信息是否正确或稍后再试。',
    tr: 'Bir şeyler yanlış gitti! Girdiğiniz bilgilerin doğruluğunu kontrol edin veya daha sonra tekrar deneyin.',
    hi: 'कुछ गलत हो गया! कृपया जांचें कि आपके द्वारा दर्ज की गई जानकारी सही है या बाद में पुनः प्रयास करें।',
    pt: 'Algo deu errado! Verifique se as informações inseridas estão corretas ou tente novamente mais tarde.',
    ja: '何かがうまくいきませんでした！入力した情報が正しいことを確認するか、後でもう一度お試しください。',
    ar: 'حدث خطأ ما! يرجى التحقق من صحة المعلومات التي أدخلتها أو حاول مرة أخرى لاحقًا.',
    fa: 'مشکلی پیش آمده است! لطفاً بررسی کنید که اطلاعات وارد شده صحیح است یا بعداً دوباره امتحان کنید.',
  },
  successRepass: {
    ru: 'На ваш email отправлен временный пароль.',
    en: 'A temporary password has been sent to your email.',
    es: 'Una contraseña temporal ha sido enviada a su correo electrónico.',
    de: 'Ein temporäres Passwort wurde an Ihre E-Mail-Adresse gesendet.',
    fr: 'Un mot de passe temporaire a été envoyé à votre email.',
    it: 'Una password temporanea è stata inviata alla tua email.',
    pl: 'Tymczasowe hasło zostało wysłane na Twój adres e-mail.',
    zh: '臨時密碼已發送到您的電子郵箱。',
    tr: 'E-postanıza geçici bir şifre gönderildi.',
    hi: 'आपके ईमेल पर एक अस्थायी पासवर्ड भेज दिया गया है।',
    pt: 'Uma senha temporária foi enviada para o seu e-mail.',
    ja: '一時的なパスワードがメールに送信されました。',
    ar: 'تم إرسال كلمة مرور مؤقتة إلى بريدك الإلكتروني.',
    fa: 'رمز عبور موقت به ایمیل شما ارسال شد.',
  },
  errorInput: {
    ru: 'Вы не заполнили обязательные поля!',
    en: 'You have not completed the required fields!',
    es: '¡No ha completado los campos obligatorios!',
    de: 'Sie haben die erforderlichen Felder nicht ausgefüllt!',
    fr: 'Vous n`avez pas rempli les champs obligatoires!',
    it: 'Non hai completato i campi richiesti!',
    pl: 'Nie wypełniłeś wymaganych pól!',
    zh: '您尚未填寫必填字段！',
    tr: 'Gerekli alanları doldurmadınız!',
    hi: 'आपने आवश्यक फ़ील्ड को पूरा नहीं किया है!',
    pt: 'Você não preencheu os campos obrigatórios!',
    ja: '必須フィールドが入力されていません！',
    ar: 'لم تقم بملء الحقول المطلوبة!',
    fa: 'شما فیلدهای مورد نیاز را تکمیل نکرده‌اید!',
  },
  errorSubmitTime: {
    ru: 'Вы успешно зарегистрировались на платформе. Необходимо время, пока наши менеджеры обработают Вашу заявку.',
    en: 'You have successfully registered on the platform. It takes time until our managers process your application.',
    es: 'Te has registrado con éxito en la plataforma. Lleva tiempo hasta que nuestro medzherov procese su solicitud.',
    de: 'Sie haben sich erfolgreich auf der Plattform registriert. Es dauert einige Zeit, bis unser Medzherov Ihre Bewerbung bearbeitet.',
    fr: 'Vous vous êtes inscrit avec succès sur la plateforme. Cela prend du temps jusqu`à ce que notre medzherov traite votre demande.',
    it: 'Ti sei registrato correttamente sulla piattaforma. Ci vuole tempo prima che il nostro medzherov elabori la tua richiesta.',
    pl: 'Pomyślnie zarejestrowałeś się na platformie. Rozpatrzenie wniosku przez naszych menedżerów zajmuje trochę czasu.',
    zh: '您已成功在平台上註冊。 我們的medzherov處理您的應用程序需要花費時間。',
    tr: 'Platforma başarıyla kayıt oldunuz. Yöneticilerimizin başvurunuzu işleme koyması zaman alır.',
    hi: 'आपने मंच पर सफलतापूर्वक पंजीकरण कर लिया है। जब तक हमारा मेड़ेरोव आपके आवेदन को संसाधित नहीं करता है, तब तक इसमें समय लगता है।',
    pt: 'Você se registrou com sucesso na plataforma. Leva tempo até que nossos gerentes processem sua inscrição.',
    ja: 'プラットフォームに正常に登録されました。 マネージャーが申請を処理するまでに時間がかかります。',
    ar: 'لقد قمت بالتسجيل بنجاح على المنصة. يستغرق الأمر بعض الوقت حتى يعالج مديرونا طلبك.',
    fa: 'شما با موفقیت در پلتفرم ثبت نام کردید. مدتی طول می‌کشد تا مدیران ما درخواست شما را بررسی کنند.',
  },
  errorGlobal: {
    ru: 'Ошибка, попробуйте позже.',
    en: 'Error, try again later.',
    es: 'Error, intente nuevamente más tarde.',
    de: 'Fehler, versuchen Sie es später erneut.',
    fr: 'Erreur, réessayez plus tard.',
    it: 'Errore, riprova più tardi.',
    pl: 'Błąd, spróbuj ponownie później.',
    zh: '錯誤，請稍後再試。',
    tr: 'Hata, daha sonra tekrar deneyin.',
    hi: 'त्रुटि, बाद में पुन: प्रयास करें।',
    pt: 'Erro, tente novamente mais tarde.',
    ja: 'エラーが発生しました。後でもう一度お試しください。',
    ar: 'خطأ، حاول مرة أخرى لاحقًا.',
    fa: 'خطا، بعداً دوباره امتحان کنید.',
  },
  errorUserExist: {
    ru: 'Данная электронная почта уже используется',
    en: 'This email is already in use',
    es: 'Este correo electrónico ya está en uso',
    de: 'Diese E-Mail-Adresse wird schon verwendet',
    fr: 'Cet e-mail est déjà utilisée',
    it: 'Questa e-mail è già in uso',
    pl: 'Ten email jest już w użyciu',
    zh: '该电子邮件已被使用',
    tr: 'Bu e-posta zaten kullanılmıştır',
    hi: 'यह ईमेल पहले से प्रयोग में है',
    pt: 'Este e-mail já está em uso',
    ja: 'このメールアドレスは既に使用されています',
    ar: 'هذا البريد الإلكتروني مستخدم بالفعل',
    fa: 'این ایمیل قبلاً استفاده شده است',
  },
  errorUserNotFound: {
    ru: 'Данного пользователя не существует',
    en: 'This user does not exist',
    es: 'Este usuario no existe',
    de: 'Dieser Benutzer existiert nicht',
    fr: 'Cet utilisateur n`existe pas',
    it: 'Questo utente non esiste',
    pl: 'Ten użytkownik nie istnieje',
    zh: '该用户不存在',
    tr: 'Böyle bir kullanıcı yoktur',
    hi: 'यह उपभोक्ता मौजूद नहीं है',
    pt: 'Este usuário não existe',
    ja: 'このユーザーは存在しません',
    ar: 'هذا المستخدم غير موجود',
    fa: 'این کاربر وجود ندارد',
  },
  errorPassword: {
    ru: 'Неверный логин или пароль',
    en: 'Wrong login or password',
    es: 'Usuario o contraseña incorrectos',
    de: 'Falsches Login oder Passwort',
    fr: 'Identifiant ou mot de passe incorrect',
    it: 'Nome utente o password errati',
    pl: 'Zły login lub hasło',
    zh: '错误的登录名或密码',
    tr: 'Hatalı kullanıcı ismi veya şifre',
    hi: 'ग़लत लॉगिन या पासवर्ड',
    pt: 'Login ou senha incorretos',
    ja: 'ログイン名またはパスワードが間違っています',
    ar: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    fa: 'ورود یا رمز عبور اشتباه است',
  },
  errorPhoneExist: {
    ru: 'Аккаунт с этим номером телефона уже существует',
    en: 'Account with this phone number already exist',
    es: 'Ya existe una cuenta con este número de teléfono',
    de: 'Ein Konto mit dieser Telefonnummer ist bereits vorhanden',
    fr: 'Un compte avec ce numéro de téléphone existe déjà',
    it: 'Esiste già un account con questo numero di telefono',
    pl: 'Konto z tym numerem telefonu już istnieje',
    zh: '具有该电话号码的帐户已存在',
    tr: 'Bu telefon numarasına sahip hesap zaten var',
    hi: 'इस फ़ोन नंबर वाला खाता पहले से मौजूद है',
    pt: 'Conta com este número de telefone já existe',
    ja: 'この電話番号のアカウントは既に存在します',
    ar: 'يوجد حساب بهذا الرقم بالفعل',
    fa: 'حساب کاربری با این شماره تلفن از قبل وجود دارد',
  },
  tooManyRequests: {
    ru: 'Ошибка, попробуйте позже.',
    en: 'Error, try again later.',
    es: 'Error, intente nuevamente más tarde.',
    de: 'Fehler, versuchen Sie es später erneut.',
    fr: 'Erreur, réessayez plus tard.',
    it: 'Errore, riprova più tardi.',
    pl: 'Błąd, spróbuj ponownie później.',
    zh: '錯誤，請稍後再試。',
    tr: 'Hata, daha sonra tekrar deneyin.',
    hi: 'त्रुटि, बाद में पुन: प्रयास करें।',
    pt: 'Erro, tente novamente mais tarde.',
    ja: 'エラーが発生しました。後でもう一度お試しください。',
    ar: 'خطأ، حاول مرة أخرى لاحقًا.',
    fa: 'خطا، بعداً دوباره امتحان کنید.',
  },
  errorCaptchaImage: {
    ru: 'Текст с картинки введен неверно. Убедитесь в правильности введенного текста и повторите попытку',
    en: 'Text from the image is entered incorrectly. Make sure the text is entered correctly and try again',
    es: 'El texto de la imagen se ingresó incorrectamente. Asegúrate de que el texto esté ingresado correctamente y vuelve a intentarlo.',
    de: 'Text aus dem Bild ist falsch eingegeben. Stellen Sie sicher, dass der Text korrekt eingegeben wurde, und versuchen Sie es erneut',
    fr: "Le texte de l'image n'est pas saisi correctement. Assurez-vous que le texte est saisi correctement et réessayez",
    it: "Il testo dell'immagine è stato inserito in modo errato. Assicurati che il testo sia stato inserito correttamente e riprova",
    pl: 'Tekst z obrazka został wpisany nieprawidłowo. Upewnij się, że tekst został wpisany poprawnie i spróbuj ponownie',
    zh: '图像中的文本输入不正确。确保文本输入正确，然后重试',
    tr: 'Resimdeki metin yanlış girildi. Girdiğiniz metnin doğru olduğundan emin olun ve tekrar deneyin',
    hi: 'छवि से पाठ ग़लत दर्ज किया गया है. सुनिश्चित करें कि पाठ सही ढंग से दर्ज किया गया है और पुनः प्रयास करें',
    pt: 'O texto da imagem foi inserido incorretamente. Certifique-se de que o texto foi inserido corretamente e tente novamente',
    ja: '画像のテキストが正しく入力されていません。テキストが正しく入力されていることを確認して、もう一度お試しください',
    ar: 'تم إدخال النص من الصورة بشكل غير صحيح. تأكد من إدخال النص بشكل صحيح وحاول مرة أخرى',
    fa: 'متن تصویر اشتباه وارد شده است. مطمئن شوید که متن به درستی وارد شده است و دوباره امتحان کنید.',
  },
  countryBlockTitle: {
    ru: 'Уважаемый пользователь!',
    en: 'Dear Customer!',
    es: '¡Estimado cliente!',
    de: 'Lieber Kunde!',
    fr: 'Cher client!',
    it: 'Caro cliente!',
    pl: 'Szanowny Kliencie!',
    zh: '尊敬的顾客！',
    tr: 'Sevgili Kullanıcı!',
    hi: 'प्रिय ग्राहक!',
    pt: 'Caro Cliente!',
    ja: '親愛なるお客様！',
    ar: 'عزيزي العميل!',
    fa: 'مشتری گرامی!',
  },
  countryBlockText: {
    ru: 'К сожалению, мы не предоставляем услуги в вашей стране!',
    en: 'Unfortunately, this service is not available in your region!',
    es: 'Desafortunadamente, este servicio no está disponible en su región.',
    de: 'Leider ist dieser Service in Ihrer Region nicht verfügbar!',
    fr: "Malheureusement, ce service n'est pas disponible dans votre région!",
    it: 'Sfortunatamente, questo servizio non è disponibile nella tua regione!',
    pl: 'Niestety ta usługa nie jest dostępna w Twoim regionie!',
    zh: '很遗憾，您所在的地区不提供此服务！',
    tr: 'Üzgünüz, ülkenizde hizmet vermiyoruz!',
    hi: 'दुर्भाग्य से, यह सेवा आपके क्षेत्र में उपलब्ध नहीं है!',
    pt: 'Infelizmente, este serviço não está disponível na sua região!',
    ja: '残念ながら、このサービスはお住まいの地域では利用できません！',
    ar: 'للأسف، هذه الخدمة غير متوفرة في منطقتك!',
    fa: 'متاسفانه این سرویس در منطقه شما در دسترس نیست!',
  },
  nameText: {
    en: 'Invalid name',
    pl: 'Błędna nazwa',
    ru: 'Недопустимое имя',
    es: 'Nombre inválido',
    de: 'Ungültiger Name',
    fr: 'Nom incorrect',
    it: 'Nome non valido',
    zh: '名称无效',
    tr: 'Geçersiz isim',
    hi: 'अमान्य नाम',
    pt: 'Nome inválido',
    ja: '無効な名前',
    ar: 'اسم غير صالح',
    fa: 'نام نامعتبر',
  },
  lastNameText: {
    en: 'Invalid last name',
    pl: 'Nieprawidłowe nazwisko',
    ru: 'Недопустимая фамилия',
    es: 'Apellido inválido',
    de: 'Ungültiger Nachname',
    fr: 'Nom de famille invalide',
    it: 'Cognome non valido',
    zh: '姓氏无效',
    tr: 'Geçersiz soyadı',
    hi: 'अमान्य उपनाम',
    pt: 'Sobrenome inválido',
    ja: '無効な苗字',
    ar: 'اسم العائلة غير صالح',
    fa: 'نام خانوادگی نامعتبر',
  },
  excludingRussian: {
    en: 'Only Latin letters, symbols and numbers are allowed',
    pl: 'Dozwolone są tylko łacińskie litery, symbole i cyfry',
    ru: 'Допустимы только латинские буквы, символы и цифры',
    es: 'Solo se permiten letras, símbolos y números en latinas.',
    de: 'Es sind nur lateinische Buchstaben, Symbole und Zahlen erlaubt',
    fr: 'Seules les lettres, symboles et chiffres latins sont autorisés',
    it: 'Sono ammessi solo lettere, simboli e numeri latini',
    zh: '只允许使用拉丁字母、符号和数字',
    tr: 'Yalnızca Latin harflerine, sembollerine ve sayılarına izin verilir',
    hi: 'केवल लैटिन अक्षरों, प्रतीकों और संख्याओं की अनुमति है',
    pt: 'Apenas letras latinas, símbolos e números são permitidos',
    ja: 'ラテン文字、記号、数字のみが許可されます',
    ar: 'يُسمح فقط بالأحرف اللاتينية والرموز والأرقام',
    fa: 'فقط حروف لاتین، نمادها و اعداد مجاز هستند',
  },
  requiredText: {
    en: 'This field is required',
    pl: 'To pole jest wymagane',
    ru: 'Это поле обязательно для заполнения',
    es: 'Este campo es requerido',
    de: 'Dieses Feld wird benötigt',
    fr: 'Ce champ est requis',
    it: 'Questo campo è obbligatorio',
    zh: '这是必填栏',
    tr: 'Bu alanın doldurulması zorunludur',
    hi: 'यह फ़ील्ड आवश्यक है',
    pt: 'Este campo é obrigatório',
    ja: 'このフィールドは必須です',
    ar: 'هذه الخانة مطلوبة',
    fa: 'این فیلد الزامی است',
  },
  minlength2: {
    en: 'Please enter at least 2 characters',
    pl: 'Proszę wpisać co najmniej 2 znaki',
    ru: 'Введите не менее 2 символов',
    es: 'Por favor ingrese al menos 2 caracteres',
    de: 'Bitte geben Sie mindestens 2 Zeichen ein',
    fr: 'Veuillez saisir au moins 2 caractères',
    it: 'Inserisci almeno 2 caratteri',
    zh: '请输入至少2个字符',
    tr: 'Lütfen en az 2 karakter giriniz',
    hi: 'कृपया कम से कम 2 अक्षर दर्ज करें',
    pt: 'Por favor, insira pelo menos 2 caracteres',
    ja: '少なくとも2文字を入力してください',
    ar: 'يرجى إدخال حرفين على الأقل',
    fa: 'لطفا حداقل ۲ کاراکتر وارد کنید',
  },
  minlength7: {
    en: 'Please enter at least 7 characters',
    pl: 'Proszę wpisać co najmniej 7 znaków',
    ru: 'Введите не менее 7 символов',
    es: 'Por favor ingrese al menos 7 caracteres',
    de: 'Bitte geben Sie mindestens 7 Zeichen ein',
    fr: 'Veuillez saisir au moins 7 caractères',
    it: 'Inserisci almeno 7 caratteri',
    zh: '请输入至少7个字符',
    tr: 'Lütfen en az 7 karakter giriniz',
    hi: 'कृपया कम से कम 7 वर्ण दर्ज करें',
    pt: 'Por favor, insira pelo menos 7 caracteres',
    ja: '少なくとも7文字を入力してください',
    ar: 'يرجى إدخال 7 أحرف على الأقل',
    fa: 'لطفا حداقل 7 کاراکتر وارد کنید',
  },
  minlength8: {
    en: 'Minimum 8 characters. Latin letters (uppercase and lowercase) and one number.',
    pl: 'Hasło musi zawierać co najmniej 8 znaków. Litery łacińskie (duże i małe) oraz jedna cyfra.',
    ru: 'Минимум 8 символов. Латинские буквы (заглавные и строчные) и одна цифра.',
    es: 'La contraseña debe tener al menos 8 caracteres. Letras latinas (mayúsculas y minúsculas) y un número.',
    de: 'Das Passwort muss mindestens 8 Zeichen lang sein. Lateinische Buchstaben (Groß - und Kleinbuchstaben) und eine Zahl.',
    fr: "Mot de passe doit être d'au moins 8 caractères. Lettres latines (majuscules et minuscules) et un chiffre.",
    it: 'La password deve essere di almeno 8 caratteri. Lettere latine (maiuscole e minuscole) e un numero.',
    zh: '密碼必須至少8個字符. 拉丁字母（大写和小写）和一个数字。',
    tr: 'Şifre 8 karakterden uzun olmalıdır. Latin harfleri (büyük ve küçük harf) ve bir rakam.',
    hi: 'पासवर्ड कम से कम 8 वर्णों का होना चाहिए. लैटिन अक्षर (अपरकेस और लोअरकेस) और एक संख्या',
    pt: 'Mínimo de 8 caracteres. Letras latinas (maiúsculas e minúsculas) e um número.',
    ja: '最低8文字。 ラテン文字（大文字と小文字）と1つの数字。',
    ar: 'الحد الأدنى 8 أحرف. أحرف لاتينية (كبيرة وصغيرة) ورقم واحد.',
    fa: 'حداقل ۸ کاراکتر. حروف لاتین (بزرگ و کوچک) و یک عدد.',
  },
  maxlength30: {
    en: 'Enter up to 30 characters',
    pl: 'Wpisz do 30 znaków',
    ru: 'Введите не более 30 символов',
    es: 'Ingrese hasta 30 caracteres',
    de: 'Geben Sie bis zu 30 Zeichen ein',
    fr: "Entrez jusqu'à 30 caractères",
    it: 'Inserisci fino a 30 caratteri',
    zh: '输入最多30个字符',
    tr: '30 karaktere kadar giriniz',
    hi: 'अधिकतम 30 वर्ण दर्ज करें',
    pt: 'Insira até 30 caracteres',
    ja: '最大30文字を入力してください',
    ar: 'أدخل ما يصل إلى 30 حرفًا',
    fa: 'تا 30 کاراکتر وارد کنید',
  },
  maxlength40: {
    en: 'Enter up to 40 characters',
    pl: 'Wpisz do 40 znaków',
    ru: 'Введите не более 40 символов',
    es: 'Ingrese hasta 40 caracteres',
    de: 'Geben Sie bis zu 40 Zeichen ein',
    fr: "Entrez jusqu'à 40 caractères",
    it: 'Inserisci fino a 40 caratteri',
    zh: '输入最多40个字符',
    tr: '40 karaktere kadar giriniz',
    hi: '40 वर्ण तक दर्ज करें',
    pt: 'Insira até 40 caracteres',
    ja: '最大40文字を入力してください',
    ar: 'أدخل ما يصل إلى 40 حرفًا',
    fa: 'تا سقف ۴۰ کاراکتر وارد کنید',
  },
  maxlength50: {
    en: 'Enter up to 50 characters',
    pl: 'Wpisz do 60 znaków',
    ru: 'Введите не более 50 символов',
    es: 'Ingrese hasta 50 caracteres',
    de: 'Geben Sie bis zu 50 Zeichen ein',
    fr: "Entrez jusqu'à 50 caractères",
    it: 'Inserisci fino a 50 caratteri',
    zh: '输入最多50个字符',
    tr: '50 karaktere kadar giriniz',
    hi: '50 वर्ण तक दर्ज करें',
    pt: 'Insira até 50 caracteres',
    ja: '最大50文字を入力してください',
    ar: 'أدخل ما يصل إلى 50 حرفًا',
    fa: 'تا ۵۰ کاراکتر وارد کنید',
  },
  emailText: {
    en: 'Invalid email address',
    pl: 'Niepoprawny adres email',
    ru: 'Недопустимый электронный адрес',
    es: 'Dirección de correo electrónico no válida',
    de: 'Ungültige E-Mail-Adresse',
    fr: 'Adresse e-mail invalide',
    it: 'indirizzo email non valido',
    zh: '无效的邮件地址',
    tr: 'Geçersiz e-posta adresi',
    hi: 'अमान्य ईमेल पता',
    pt: 'Endereço de e-mail inválido',
    ja: '無効なメールアドレス',
    ar: 'عنوان البريد الإلكتروني غير صالح',
    fa: 'آدرس ایمیل نامعتبر',
  },
  equalToText: {
    en: 'Password mismatch',
    pl: 'Hasło różni się',
    ru: 'Пароли не совпадают',
    es: 'Contraseña no coincide',
    de: 'Die Passwörter stimmen nicht überein',
    fr: 'Non concordance des mots de passe',
    it: 'Mancata corrispondenza della password',
    zh: '密码不符合',
    tr: 'Şifreler eşleşmiyor',
    hi: 'पासवर्ड का मेल नहीं हुआ',
    pt: 'As senhas não coincidem',
    ja: 'パスワードが一致しません',
    ar: 'كلمة المرور غير متطابقة',
    fa: 'عدم تطابق رمز عبور',
  },
  errorPasswordText: {
    en: 'Password does not meet requirements',
    pl: 'Hasło Nie spełnia wymagań',
    ru: 'Пароль не соответствует требованиям',
    es: 'La contraseña no cumple los requisitos',
    de: 'Passwort entspricht nicht der Anforderungen',
    fr: 'Le mot de passe ne répond pas aux exigences',
    it: 'La password non soddisfa i requisiti',
    zh: '密码不符合要求',
    tr: 'Şifre taleplere uymuyor',
    hi: 'पासवर्ड आवश्यकताओं को पूरा नहीं करता है',
    pt: 'A senha não atende aos requisitos',
    ja: 'パスワードが要件を満たしていません',
    ar: 'كلمة المرور لا تفي بالمتطلبات',
    fa: 'رمز عبور الزامات را برآورده نمی‌کند',
  },
  openTwoauthstepPopupRules: {
    en: 'Code is incorrect. Please try again.',
    pl: 'Kod jest nieprawidłowy. Proszę spróbuj ponownie.',
    ru: 'Код указан неверно. Пожалуйста, попробуйте еще раз.',
    es: 'El codigo esta mal. Inténtalo de nuevo.',
    de: 'Der Code ist falsch. Bitte versuche es erneut.',
    fr: 'Le code est faux. Veuillez réessayer.',
    it: 'Il codice è sbagliato. Per favore riprova.',
    zh: '代码错误。 请再试一次。',
    tr: 'Kod yanlış. Lütfen tekrar deneyin.',
    hi: 'कोड गलत है। कृपया पुन: प्रयास करें।',
    pt: 'O código está incorreto. Por favor, tente novamente.',
    ja: 'コードが間違っています。 もう一度お試しください。',
    ar: 'الكود غير صحيح. حاول مرة أخرى.',
    fa: 'کد اشتباه است. لطفا دوباره امتحان کنید.',
  },
  uncorrectSymbols: {
    en: 'Text contains forbidden characters',
    pl: 'Tekst zawiera zabronione znaki',
    ru: 'Текст содержит запрещенные символы',
    es: 'El texto contiene caracteres prohibidos',
    de: 'Der Text enthält verbotene Zeichen',
    fr: 'Le texte contient des caractères interdits',
    it: 'Il testo contiene caratteri non consentiti',
    zh: '文本包含禁止字符',
    tr: 'Metin yasaklanmış karakterler içeriyor',
    hi: 'पाठ में निषिद्ध वर्ण हैं',
    pt: 'O texto contém caracteres proibidos',
    ja: 'テキストに禁止文字が含まれています',
    ar: 'يحتوي النص على أحرف محظورة',
    fa: 'متن حاوی کاراکترهای ممنوعه است',
  },
  coipsTitle: {
    ru: 'Пoлитикa в oтнoшeнии кoнфликтa интepecoв',
    en: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    es: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    de: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    fr: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    it: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    pl: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    zh: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    tr: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    hi: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    pt: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    ar: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    ja: 'Cоnfliсt оf Interest Pоliсy Stаtement',
    fa: 'Cоnfliсt оf Interest Pоliсy Stаtement',
  },
  rcpTitle: {
    ru: 'Пoлитикa вoзвpaтa cpeдcтв и oтмeны зaчиcлeния cpeдcтв',
    en: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    es: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    de: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    fr: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    it: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    pl: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    zh: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    tr: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    hi: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    pt: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    ar: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    ja: 'Rеfund & Cаnсеllаtіоn Pоlісy',
    fa: 'Rеfund & Cаnсеllаtіоn Pоlісy',
  },
  rdnTitle: {
    ru: 'Зaявлeниe o рacкрытии риcкoв',
    en: 'Risk Disсlоsure Nоtiсe',
    es: 'Risk Disсlоsure Nоtiсe',
    de: 'Risk Disсlоsure Nоtiсe',
    fr: 'Risk Disсlоsure Nоtiсe',
    it: 'Risk Disсlоsure Nоtiсe',
    pl: 'Risk Disсlоsure Nоtiсe',
    zh: 'Risk Disсlоsure Nоtiсe',
    tr: 'Risk Disсlоsure Nоtiсe',
    hi: 'Risk Disсlоsure Nоtiсe',
    pt: 'Risk Disсlоsure Nоtiсe',
    ar: 'Risk Disсlоsure Nоtiсe',
    ja: 'Risk Disсlоsure Nоtiсe',
    fa: 'Risk Disсlоsure Nоtiсe',
  },
  uaTitle: {
    ru: 'Пoльзoвaтeльcкoe coглaшeниe',
    en: 'Usеr Аgrееmеnt',
    es: 'Usеr Аgrееmеnt',
    de: 'Usеr Аgrееmеnt',
    fr: 'Usеr Аgrееmеnt',
    it: 'Usеr Аgrееmеnt',
    pl: 'Usеr Аgrееmеnt',
    zh: 'Usеr Аgrееmеnt',
    tr: 'Usеr Аgrееmеnt',
    hi: 'Usеr Аgrееmеnt',
    pt: 'Usеr Аgrееmеnt',
    ar: 'Usеr Аgrееmеnt',
    ja: 'Usеr Аgrееmеnt',
    fa: 'Usеr Аgrееmеnt',
  },
  twoFaIncorrectCode: {
    en: 'Code is incorrect. Please try again.',
    pl: 'Kod jest nieprawidłowy. Proszę spróbuj ponownie.',
    ru: 'Неверный код, попробуйте еще раз.',
    es: 'El codigo esta mal. Inténtalo de nuevo.',
    de: 'Der Code ist falsch. Bitte versuche es erneut.',
    fr: 'Le code est faux. Veuillez réessayer.',
    it: 'Il codice è sbagliato. Per favore riprova.',
    zh: '代码错误。 请再试一次。',
    tr: 'Kod yanlış. Lütfen tekrar deneyin.',
    hi: 'कोड गलत है। कृपया पुन: प्रयास करें।',
    ar: 'الكود غير صحيح. من فضلك حاول مرة أخرى.',
    pt: 'O código está incorreto. Por favor, tente novamente.',
    ja: 'コードが間違っています。もう一度お試しください。',
    fa: 'کد اشتباه است. لطفا دوباره امتحان کنید.',
  },
  ppTitle: {
    ru: 'Заявление о конфиденциальности и политика в отношении файлов cookie',
    en: 'Statement on Privacy and Cookie Policy',
    es: 'Statement on Privacy and Cookie Policy',
    de: 'Statement on Privacy and Cookie Policy',
    fr: 'Statement on Privacy and Cookie Policy',
    it: 'Statement on Privacy and Cookie Policy',
    pl: 'Statement on Privacy and Cookie Policy',
    zh: 'Statement on Privacy and Cookie Policy',
    tr: 'Statement on Privacy and Cookie Policy',
    hi: 'Statement on Privacy and Cookie Policy',
    pt: 'Statement on Privacy and Cookie Policy',
    ar: 'Statement on Privacy and Cookie Policy',
    ja: 'Statement on Privacy and Cookie Policy',
    fa: 'Statement on Privacy and Cookie Policy',
  },
  tuTitle: {
    ru: 'Условия использования сайта',
    en: 'Terms of Website Use',
    es: 'Terms of Website Use',
    de: 'Terms of Website Use',
    fr: 'Terms of Website Use',
    it: 'Terms of Website Use',
    pl: 'Terms of Website Use',
    zh: 'Terms of Website Use',
    tr: 'Terms of Website Use',
    hi: 'Terms of Website Use',
    pt: 'Terms of Website Use',
    ar: 'Terms of Website Use',
    ja: 'Terms of Website Use',
    fa: 'Terms of Website Use',
  },
  tableFooterText: {
    ru: '*Часы открытия и закрытия торгов указаны по UTC+0',
    en: '*Opening and closing hours of trading are indicated in UTC+0',
    es: '*Los horarios de apertura y cierre de operaciones se indican en UTC+0',
    de: '*Die Eröffnungs - und Schlusszeiten des Handels werden in UTC+0 angegeben',
    fr: "*Les heures d'ouverture et de fermeture des marchés sont indiquées en UTC+0",
    it: '*Gli orari di apertura e chiusura delle negoziazioni sono indicati in UTC+0',
    pl: '*Godziny otwarcia i zamknięcia handlu podawane są w formacie UTC+0',
    zh: '*交易開市和收市時間以 UTC+0 表示',
    tr: '*Alım satım açılış ve kapanış saatleri UTC+0 saatine göre belirtilmiştir',
    hi: '*ट्रेडिंग के खुलने और बंद होने का समय UTC+0 में दर्शाया गया है',
    pt: '*Os horários de abertura e fechamento das negociações são indicados em UTC+0',
    ja: '*取引の開始および終了時刻はUTC+0で表示されます',
    ar: '*يتم عرض أوقات فتح وإغلاق التداول حسب توقيت UTC+0',
    fa: '*ساعات باز و بسته شدن معاملات بر اساس UTC+0 نشان داده شده است',
  },
};
